### ISSUE TITLE
Security Features list

### ISSUE THREAD

**Issue by danielflachica** [Marlcelo/Shoeversity#124]
Make a list of security features (All from the PPTs ni sir) that we need to implement.

Either that or make new issues with the title format "Security - <issue>" AND add the "Security" label to them

**Comment by chelseymedina** [comment]
Please always check this doc? hahahah
https://docs.google.com/document/d/1nD6o0DynDVUXlVV4RO8RQmZZ9npjLvHXKgYmJKN2QoM/edit

it contains the checklist of needed features!
