### ISSUE TITLE
XXE Attacks - prevention

### ISSUE THREAD

**Issue by danielflachica** [Marlcelo/Shoeversity#162]
As per PHP User Manual, prevent XXE Attacks with: 

`libxml_disable_entity_loader(true);`

**Comment by danielflachica** [comment]
OWASP docs: https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet

**Comment by Marlcelo** [comment]
NOT APPLICABLE?
