### ISSUE TITLE
Register button (user & brand)redirect path 

### ISSUE THREAD

**Issue by chelseymedina** [Marlcelo/Shoeversity#52]
Pumupunta siya in a different page, a database file which is not supposed to be shown to the user

**Comment by chelseymedina** [comment]
Pumupunta siya in a different page, a database file which is not supposed to be shown to the user

**Comment by Marlcelo** [comment]
The User, when registered successfully, will now be redirected to the landing page for all logged in users. AUTOMATICALLY NA SIYA MAGLLOGIN AFTER REGISTRATION

**Comment by Marlcelo** [comment]
The Brand on the other hand will NOT BE REDIRECTED TO THE LOGGED IN PAGE as hindi pa sila verified

**Comment by Marlcelo** [comment]
All good as of 4/2/2018.
Please refer to my commits for information regarding the mechanics
